packages:
  - 'apps/*'

overrides:
  multer: ^2.2.0
  undici: ^6.27.0

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  msw: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - 'unrs-resolver'
  - 'esbuild'
  - 'msw'
