#!/bin/bash
# Setup AI Skills for ididntcatchthat
# Configures AI coding assistants:
#   - opencode: .claude/skills/ symlink
#   - GitHub Copilot: .github/copilot-instructions.md symlink → AGENTS.md
#                     .github/skills/ symlink → skills/
#
# Usage:
#   bash skills/setup.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
SKILLS_SOURCE="$SCRIPT_DIR"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

add_to_gitignore() {
    local pattern="$1"
    local gitignore_file="$REPO_ROOT/.gitignore"
    local header="# AI coding assistants (generated by skills/setup.sh)"

    [ ! -f "$gitignore_file" ] && touch "$gitignore_file"

    if ! grep -qxF "$pattern" "$gitignore_file"; then
        if ! grep -qxF "$header" "$gitignore_file"; then
            printf "\n\n%s\n" "$header" >> "$gitignore_file"
        fi
        echo "$pattern" >> "$gitignore_file"
        echo -e "${GREEN}  ✓ Added $pattern to .gitignore${NC}"
    fi
}

# ─── opencode (.claude/skills/) ───────────────────────────────────────────────
echo -e "${YELLOW}[1/2] Setting up opencode...${NC}"

mkdir -p "$REPO_ROOT/.claude"
TARGET="$REPO_ROOT/.claude/skills"

[ -L "$TARGET" ] && rm "$TARGET"
[ -d "$TARGET" ] && mv "$TARGET" "$REPO_ROOT/.claude/skills.backup.$(date +%s)"

ln -s "$SKILLS_SOURCE" "$TARGET"
add_to_gitignore ".claude/skills"
echo -e "${GREEN}  ✓ .claude/skills -> skills/${NC}"

# ─── GitHub Copilot (.github/copilot-instructions.md + .github/skills/) ──────
echo -e "${YELLOW}[2/2] Setting up GitHub Copilot...${NC}"

mkdir -p "$REPO_ROOT/.github"

# copilot-instructions.md → AGENTS.md
COPILOT_TARGET="$REPO_ROOT/.github/copilot-instructions.md"
[ -L "$COPILOT_TARGET" ] && rm "$COPILOT_TARGET"
ln -sf "../AGENTS.md" "$COPILOT_TARGET"
add_to_gitignore ".github/copilot-instructions.md"
echo -e "${GREEN}  ✓ .github/copilot-instructions.md -> AGENTS.md${NC}"

# .github/skills/ → skills/
COPILOT_SKILLS="$REPO_ROOT/.github/skills"
[ -L "$COPILOT_SKILLS" ] && rm "$COPILOT_SKILLS"
[ -d "$COPILOT_SKILLS" ] && mv "$COPILOT_SKILLS" "$REPO_ROOT/.github/skills.backup.$(date +%s)"
ln -s "$SKILLS_SOURCE" "$COPILOT_SKILLS"
add_to_gitignore ".github/skills"
echo -e "${GREEN}  ✓ .github/skills -> skills/${NC}"

# ─── Summary ─────────────────────────────────────────────────────────────────
SKILL_COUNT=$(find "$SKILLS_SOURCE" -maxdepth 2 -name "SKILL.md" | wc -l | tr -d ' ')

echo ""
echo -e "${GREEN}✅ Done — $SKILL_COUNT skills configured${NC}"
echo ""
echo "  • opencode:        .claude/skills/"
echo "  • GitHub Copilot:  .github/copilot-instructions.md + .github/skills/"
echo ""
echo -e "${BLUE}Restart your AI assistant to load the skills.${NC}"
echo -e "${BLUE}AGENTS.md is the source of truth — changes reflect automatically via symlinks.${NC}"
